---
title: "Workflow"
author: "Volker Schmid"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Workflow for 3D SIM nucleome analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bioimagetools)
library(nucim)
```

## Workflow example

# Installation
```{r eval=FALSE, collapse=TRUE}
setRepositories(ind=c(1,2))
install.packages("nucim")
library(bioimagetools)
library(nucim)
```

# Read image and mask from DAPI
```{r cache=TRUE, echo=TRUE, warning=FALSE, collapse=TRUE}
img = readTIF("http://ex.volkerschmid.de/cell.tif")
sections = dim(img)[4]
x = y = 0.395
z = 0.125
blue = img[,,3,] 
mask = dapimask(blue, c(x,y,z)*dim(img)[1:3], thresh="auto")
```

# Chromatin compaction classification
```{r cache=TRUE, echo=TRUE, warning=FALSE, collapse=TRUE}
classes = classify(blue, mask, 7, beta=0.1, z=x/z)
tab<-table.n(classes, 7, percentage=TRUE)
barplot(tab, ylab="percentage", xlab="chromatin compaction level",col=heatmap7())
par(pty="s")
img(classes, z=16, col=heatmap7(), mask=mask)
writeTIF(classes, "classes.tif")
```

# Distances of chromatin compaction classes
```{r cache=TRUE, echo=TRUE, warning=FALSE, collapse=TRUE, eval=FALSE}
classes<-readClassTIF("classes.tif")
distances = nearestClassDistances(classes,  voxelsize=c(x,y,z), classes=7, cores=24L)
save(distances,file="distances.Rdata")
plotNearestClassDistances(distances, method="min",ylim=c(0,.1),qu=.01)
tiff(filename="fig-vs-7.tiff",width=960)#remove
plotNearestClassDistances(distances, method="quantile",ylim=c(0,.22),qu=.01)
dev.off()#remove
tiff(filename="fig-vs-6.tiff",width=960)#remove
plotNearestClassDistances(distances, method="boxplot",ylim=c(0,1.5))
dev.off()#remove
```

# Map spots to classes
```{r cache=TRUE, collapse=TRUE, warning=FALSE}
red = img[,,1,]
green = img[,,2,]
cc1<-colors.in.classes(classes,red,green,mask,7,type="thresh",plot=TRUE,col1="red",col2="green",thresh1=0.05,thresh2=0.05,test="Wilcoxon",ylim=c(0,.5),xlab="chromatin compaction levels",ylab="percentage")
cc2<-colors.in.classes(classes,red,green,mask,7,type="intensity",plot=TRUE,col1="red",col2="green",thresh1=0.05,thresh2=0.05,test="Wilcoxon",ylim=c(0,.5),xlab="chromatin compaction levels",ylab="percentage")
```
```{r cache=TRUE, echo=TRUE, warning=FALSE, collapse=TRUE}
spots<-spots.combined(red=red,green=green,mask=mask,size=c(x,y,z),full.voxel=FALSE,thresh.offset=0.05)
```
```{r cache=TRUE, collapse=TRUE, warning=FALSE}
cc<-colors.in.classes(classes,spots$red,spots$green,mask,7,type="i",plot=TRUE,col1="red",col2="green",test="Wilcoxon",ylim=c(0,.8),xlab="chromatin compaction levels",ylab="percentage")
```
